### ISSUE TITLE
Segmentation fault / bus error

### ISSUE THREAD

**Issue by kdping** [aabc/equihash-zcash-c#2]
after done with READ instructions, I run cli api as described primarily:
> ./basicSolver-opt -n 200 -k 9 -i input.bin
then errors occured as stated in title, and CPU usage reaches 100%. input.bin is original one from this project, below are screen outputs:
: n 200, k 9
: collisionBitLength 20
: collisionByteLength 3
: hashLength 30
: indicesPerHashOutput 2
: hashOutput 50
: fullWidth 1030
: initSize 2097152 (memory 2160066560)
Generating first list
Round 1:
- Sorting list (size 2097152, 71303168)
- Finding collisions
Round 2:
- Sorting list (size 2097866, 73425310)
- Finding collisions
Round 3:
- Sorting list (size 2096897, 83875880)
- Finding collisions
Round 4:
- Sorting list (size 2093984, 110981152)
- Finding collisions
Round 5:
- Sorting list (size 2089702, 171355564)
- Finding collisions
Round 6:
- Sorting list (size 2080602, 297526086)
- Finding collisions
Round 7:
- Sorting list (size 2062335, 552705780)
- Finding collisions
Round 8:
- Sorting list (size 2023493, 1054239853)
- Finding collisions
Final round:
- Sorting list (size 1934638, 1992677140)
- Finding collisions
+ collision of size 1344 (1344)
 1311745 924161 1837314 211714 1360386 2089986 848898 1726979 1199108 290052 761092 1548292 1103620 1507589 1220357 1980678 687110 37382 142087 344327 949255 1055752 1602056 1530889 1077769 1098250 1773323 1462284 2053900 750348 847118 214031 690191 1348881 2070033 1234194 615443 571923 381459 566549 304661 838421 1848342 1005846 910361 470299 537883 1154587 50715 1384988 144413 955421 1181982 929567 1540383 1915680 1415968 984609 1836577 338721 901665 1746979 380451 395812 14628 619300 1345060 421157 2024486 1570598 1506854 727847 141351 1417767 270120 1058344 809000 960552 1621544 49961 1342250 1848875 1527340 1236524 1888045 1017903 1605936 822576 574512 812338 946994 1009460 1971765 143413 1014325 718902 1846839 1983031 1608503 2093879 948792 1679416 1585465 1139001 2081593 257337 2090810 1913659 245819 512571 661308 1671996 1198909 452413 1275454 1145406 241982 898622 985919 1720127 2019135 1010496 487744 1539648 1950528 1008705 2017601 1637186 868163 570691 838979 1046595 140612 1947716 1526341 696901 235846 1572936 1835592 126024 1800009 812874 751436 300108 439628 590413 1856589 113741 1891149 324941 1178445 1355854 720462 1590607 305487 1460304 814672 573520 1170768 1531473 681041 1008722 732499 1136723 1744211 1320277 1854805 443477 584277 923478 1521238 1074262 1821014 1841240 1454424 1649243 19547 829531 1120348 737116 1017180 1082716 1495644 130396 330078 807518 1512031 1155167 22369 619873 85346 1594978 139619 613219 1074276 1039973 130150 1380455 261991 542056 1262952 103528 699496 1626728 1885033 1439081 1499242 1716331 185195 2050925 879469 1880429 1465710 2009454 1425518 225391 896624 710257 5234 390258 2024307 1782388 491893 622965 800119 1614200 196216 449145 908921 732538 1796986 1417850 1436283 1728124 791166 799358 290430 1992319 2069631 123263 7808 1965184 1869185 1868162 1822850 975746 1724291 424323 1219715 1066884 886404 1511045 1529733 2054533 379269 1000838 1669766 1939846 1491334 476807 526216 607625 286601 97929 710793 264586 1723274 2085258 581258 164491 168075 1894028 1327757 1886349 380813 1040013 517005 396430 1265038 1305998 2093966 862607 132496 1379472 1657233 1657489 1014673 968593 1563281 91026 1846676 958868 266389 531861 2006936 649368 846488 1094298 906906 1926556 1065629 950685 1639070 1982110 1404574 1356447 557216 2075040 313248 1510050 1221026 566690 844194 932003 1065123 600740 1721508 1994404 127396 1206693 683941 118181 1895589 1205926 1143206 1537191 1473191 39847 1936040 701608 468393 1399209 1430441 1235881 779433 438186 1562282 1102507 387755 278700 1944748 27821 1299373 2087853 1836974 1579182 1085102 1152942 1816494 1830062 1507504 1001648 1416368 462257 287409 291249 2080945 1678002 645042 925619 1407411 1192116 1650868 262068 630197 814774 1672374 520118 51639 1252792 1654968 223928 1927864 344249 1805497 129465 426426 688826 1109946 1964218 1837755 1285819 489404 882620 525757 111293 792254 1153214 504254 783294 419775 1102528 1377473 1774274 1467330 950466 1182915 976323 1518020 1540292 1627077 2046150 1392070 16070 976838 197063 1648584 1205192 747208 328650 409035 1929932 1084620 1806796 1793741 5070 342478 1881806 1426894 444879 1483728 846544 516049 133586 1961938 574163 158420 1022164 717780 1608405 758230 171734 752088 1842137 999129 1663450 1419738 1628378 1324763 2012 365020 875230 1759966 244959 1762015 609760 2051041 426721 113377 1075682 1958115 2047204 254949 255461 295910 1628134 1620967 1844968 17896 1855720 1680617 1648106 934890 1066986 100074 781034 1852140 322284 405998 400879 277743 936687 1731823 1042671 588015 474096 1612016 460785 408305 1142258 369138 1433074 1436914 1217779 278260 348660 413173 1612789 1809397 1962997 211446 249846 988919 1945335 1238007 961272 833528 1053433 2051065 1920761 1213690 722683 1258235 1655291 161787 975099 792828 263677 102909 1095678 1705215 1486079
a0200b868078120433b02a61017f90099e805a5a039260211b41173a097a00486b825c041653e0be390653e030248184560e5410773e03c070230e41175c0983904c3082b61e176500cfab862dcc319da1c3440f54407d25447f2c232d5124b209a2e84cba4268a5152530ab32c578682cf59166f20c9cb46d06a3719e1b0630dd488704683ae941d9048f38bc7ef023fd3b20acd903c188780c4252b216e110eaa08cb9c4660a2401c9225cc9290c4866d25f72135fdc9adfc4cb1b2711413d6889c83e510262862c143aa0a317c500c329a3d9570d8aee9c592de2ce6796be20bf10260c8d30462183194c9ce664f6734f0b1a88c0d5ef46aaf836e171bf908df1166fff33773d1c6680e30627316139fe19c8fb4e7fce75d333b1e01d9f48ed42e799833c9259e9b9cf66ec7d17a3e1d89f36d8f9e167fa3f3ff679fbdad00ee28177e40ee1a03d9107d92838fb4269fa1a2d50d99a86ff843112a276e112e948aaa2451cca3600123804901ec48dbba4b19d296ee984944c35aa62409378a89a1bc4de6da693d5363f69b4b04e57f2761153c9529f64850637282301423baa175e5153228bd914965aa715853d4ea9d0955789aaa6c4554752ab85d5ae6cad06456de4ab706162c62b192a5b0262db2a16e230b8b3f5c7c2ae421572da4b81fd5c284af31497ae24bf1a05f02bb0a5d58429ac585662110b1a56d8e0c8c8fde650fe3354419c7fece845689a2b40651a1558d18d268e61b4d7d5a6dc0d5a306b169b5fd2db5ad6dbcb16db2eb77aa5bab80dc3706f6d7382b59c4028e45f472f71b9ecc9d0f02ea9817561abbe285e05fcf06da796ef3cacb5eb6d6f55a27aaf53de979f1824fcc327e2373f7999fff28fe1e17f00f4077f20390b03c8182de8413b8e0b49f066798394e41c11e11b0d0970e85babc2fd6614b930af4586cbd4376661ad830c74687403c42516248bf1217e8956c4490262b49715fd18a46f450a0a2c52117ce68ca2146f32234b9f1afde8d3f1c698323a69b1d3ed8eff9c734a63c40b2150c90ca4c8e52a45ef722ec791bed48858e4b85b28ea1942084aa07657d3f309e8986754c42ca69bad35d659c8214eba06772053de3e9eab74f52ca7d10141fa9a0263d05c2a8a543448a5a2670d138e28e0814692aa4d225279ba903e349269a5537d28736979d94b266a68b8d35dd29ecf54e09ba7ec5542ad2a0e4b53559a9ae9d4cb6ea57c9526afaabeb55434aacbd556440aced65601b2b67a75bfdbade03d76062ba11d5d197aeddbd76fb2bae0160f48b0ace581c36c48c562471b1fe058e66ac93af64e1fb3abcd9c8c2d3261683ffb44cedab1badb3096c7efb6064dbcc76e32817036ab8eb55c1502e7719721f9b9340dd2a0aea1df75df8bae055dce7aeceef78d77bc402de86caf582d7d198be3d8df2fcef8ccf7f0d2c0a8260ec4b0acc784e80c290661bb970ee5389780c4c69e2fce31aa7b8c03ec6773e30c071f24f91263c85b364140f28c7b97d72cc846666e47336bd9a013ce29ce772db3ab8b9c6c9cfb51e833ab40fbfa2209d2ef7e9230b4c4d5a8f98d4579ea622b55723ac29ed65bcec706f65e7db3961daad4ed63636a86db6007dc2c8ee356b7b5b5bc3bcdfd716fa53783e97c2682e10dd70c1a78bbc1c7f3ce41f1f28f9794907cd8d7e6c5df3f09ba008bd1c50e8cd274e497a9c87d5047ea0c3752fabab885d84eaec318f71877bc879dee4aefd3677bfa3bd1f1de73bf0c4c781c1fc4c75e316df22d0f95777cabd9e5294f321f7a1547d0c9beb89bf5dcdfaf7cfd4673ec3cff678b7bf6bbde5c7eeeaaf865bfc404be7e97f3d4ef99427d2c1bee665f7941fb13bfdbb83ed831f8405fd0c8fec2dffb409ff6acff
Bus error (core dumped)

segamentation fault:
: n 200, k 9
: collisionBitLength 20
: collisionByteLength 3
: hashLength 30
: indicesPerHashOutput 2
: hashOutput 50
: fullWidth 1030
: initSize 2097152 (memory 2160066560)
Generating first list
Round 1:
- Sorting list (size 2097152, 71303168)
- Finding collisions
Round 2:
- Sorting list (size 2097866, 73425310)
- Finding collisions
Round 3:
- Sorting list (size 2096897, 83875880)
- Finding collisions
Round 4:
- Sorting list (size 2093984, 110981152)
- Finding collisions
Round 5:
- Sorting list (size 2089702, 171355564)
- Finding collisions
Round 2:
- Sorting list (size 2097866, 73425310)
- Finding collisions
Round 3:
- Sorting list (size 2096897, 83875880)
- Finding collisions
Round 4:
- Sorting list (size 2093984, 110981152)
- Finding collisions
Round 5:
- Sorting list (size 2089702, 171355564)
- Finding collisions
Round 6:
- Sorting list (size 2080602, 297526086)
- Finding collisions
Round 7:
- Sorting list (size 2062335, 552705780)
- Finding collisions
Round 8:
- Sorting list (size 2023493, 1054239853)
- Finding collisions
Final round:
- Sorting list (size 1934638, 1992677140)
- Finding collisions
+ collision of size 1344 (1344)
 1311745 924161 1837314 211714 1360386 2089986 848898 1726979 1199108 290052 761092 1548292 1103620 1507589 1220357 1980678 687110 37382 142087 344327 949255 1055752 1602056 1530889 1077769 1098250 1773323 1462284 2053900 750348 847118 214031 690191 1348881 2070033 1234194 615443 571923 381459 566549 304661 838421 1848342 1005846 910361 470299 537883 1154587 50715 1384988 144413 955421 1181982 929567 1540383 1915680 1415968 984609 1836577 338721 901665 1746979 380451 395812 14628 619300 1345060 421157 2024486 1570598 1506854 727847 141351 1417767 270120 1058344 809000 960552 1621544 49961 1342250 1848875 1527340 1236524 1888045 1017903 1605936 822576 574512 812338 946994 1009460 1971765 143413 1014325 718902 1846839 1983031 1608503 2093879 948792 1679416 1585465 1139001 2081593 257337 2090810 1913659 245819 512571 661308 1671996 1198909 452413 1275454 1145406 241982 898622 985919 1720127 2019135 1010496 487744 1539648 1950528 1008705 2017601 1637186 868163 570691 838979 1046595 140612 1947716 1526341 696901 235846 1572936 1835592 126024 1800009 812874 751436 300108 439628 590413 1856589 113741 1891149 324941 1178445 1355854 720462 1590607 305487 1460304 814672 573520 1170768 1531473 681041 1008722 732499 1136723 1744211 1320277 1854805 443477 584277 923478 1521238 1074262 1821014 1841240 1454424 1649243 19547 829531 1120348 737116 1017180 1082716 1495644 130396 330078 807518 1512031 1155167 22369 619873 85346 1594978 139619 613219 1074276 1039973 130150 1380455 261991 542056 1262952 103528 699496 1626728 1885033 1439081 1499242 1716331 185195 2050925 879469 1880429 1465710 2009454 1425518 225391 896624 710257 5234 390258 2024307 1782388 491893 622965 800119 1614200 196216 449145 908921 732538 1796986 1417850 1436283 1728124 791166 799358 290430 1992319 2069631 123263 7808 1965184 1869185 1868162 1822850 975746 1724291 424323 1219715 1066884 886404 1511045 1529733 2054533 379269 1000838 1669766 1939846 1491334 476807 526216 607625 286601 97929 710793 264586 1723274 2085258 581258 164491 168075 1894028 1327757 1886349 380813 1040013 517005 396430 1265038 1305998 2093966 862607 132496 1379472 1657233 1657489 1014673 968593 1563281 91026 1846676 958868 266389 531861 2006936 649368 846488 1094298 906906 1926556 1065629 950685 1639070 1982110 1404574 1356447 557216 2075040 313248 1510050 1221026 566690 844194 932003 1065123 600740 1721508 1994404 127396 1206693 683941 118181 1895589 1205926 1143206 1537191 1473191 39847 1936040 701608 468393 1399209 1430441 1235881 779433 438186 1562282 1102507 387755 278700 1944748 27821 1299373 2087853 1836974 1579182 1085102 1152942 1816494 1830062 1507504 1001648 1416368 462257 287409 291249 2080945 1678002 645042 925619 1407411 1192116 1650868 262068 630197 814774 1672374 520118 51639 1252792 1654968 223928 1927864 344249 1805497 129465 426426 688826 1109946 1964218 1837755 1285819 489404 882620 525757 111293 792254 1153214 504254 783294 419775 1102528 1377473 1774274 1467330 950466 1182915 976323 1518020 1540292 1627077 2046150 1392070 16070 976838 197063 1648584 1205192 747208 328650 409035 1929932 1084620 1806796 1793741 5070 342478 1881806 1426894 444879 1483728 846544 516049 133586 1961938 574163 158420 1022164 717780 1608405 758230 171734 752088 1842137 999129 1663450 1419738 1628378 1324763 2012 365020 875230 1759966 244959 1762015 609760 2051041 426721 113377 1075682 1958115 2047204 254949 255461 295910 1628134 1620967 1844968 17896 1855720 1680617 1648106 934890 1066986 100074 781034 1852140 322284 405998 400879 277743 936687 1731823 1042671 588015 474096 1612016 460785 408305 1142258 369138 1433074 1436914 1217779 278260 348660 413173 1612789 1809397 1962997 211446 249846 988919 1945335 1238007 961272 833528 1053433 2051065 1920761 1213690 722683 1258235 1655291 161787 975099 792828 263677 102909 1095678 1705215 1486079
a0200b868078120433b02a61017f90099e805a5a039260211b41173a097a00486b825c041653e0be390653e030248184560e5410773e03c070230e41175c0983904c3082b61e176500cfab862dcc319da1c3440f54407d25447f2c232d5124b209a2e84cba4268a5152530ab32c578682cf59166f20c9cb46d06a3719e1b0630dd488704683ae941d9048f38bc7ef023fd3b20acd903c188780c4252b216e110eaa08cb9c4660a2401c9225cc9290c4866d25f72135fdc9adfc4cb1b2711413d6889c83e510262862c143aa0a317c500c329a3d9570d8aee9c592de2ce6796be20bf10260c8d30462183194c9ce664f6734f0b1a88c0d5ef46aaf836e171bf908df1166fff33773d1c6680e30627316139fe19c8fb4e7fce75d333b1e01d9f48ed42e799833c9259e9b9cf66ec7d17a3e1d89f36d8f9e167fa3f3ff679fbdad00ee28177e40ee1a03d9107d92838fb4269fa1a2d50d99a86ff843112a276e112e948aaa2451cca3600123804901ec48dbba4b19d296ee984944c35aa62409378a89a1bc4de6da693d5363f69b4b04e57f2761153c9529f64850637282301423baa175e5153228bd914965aa715853d4ea9d0955789aaa6c4554752ab85d5ae6cad06456de4ab706162c62b192a5b0262db2a16e230b8b3f5c7c2ae421572da4b81fd5c284af31497ae24bf1a05f02bb0a5d58429ac585662110b1a56d8e0c8c8fde650fe3354419c7fece845689a2b40651a1558d18d268e61b4d7d5a6dc0d5a306b169b5fd2db5ad6dbcb16db2eb77aa5bab80dc3706f6d7382b59c4028e45f472f71b9ecc9d0f02ea9817561abbe285e05fcf06da796ef3cacb5eb6d6f55a27aaf53de979f1824fcc327e2373f7999fff28fe1e17f00f4077f20390b03c8182de8413b8e0b49f066798394e41c11e11b0d0970e85babc2fd6614b930af4586cbd4376661ad830c74687403c42516248bf1217e8956c4490262b49715fd18a46f450a0a2c52117ce68ca2146f32234b9f1afde8d3f1c698323a69b1d3ed8eff9c734a63c40b2150c90ca4c8e52a45ef722ec791bed48858e4b85b28ea1942084aa07657d3f309e8986754c42ca69bad35d659c8214eba06772053de3e9eab74f52ca7d10141fa9a0263d05c2a8a543448a5a2670d138e28e0814692aa4d225279ba903e349269a5537d28736979d94b266a68b8d35dd29ecf54e09ba7ec5542ad2a0e4b53559a9ae9d4cb6ea57c9526afaabeb55434aacbd556440aced65601b2b67a75bfdbade03d76062ba11d5d197aeddbd76fb2bae0160f48b0ace581c36c48c562471b1fe058e66ac93af64e1fb3abcd9c8c2d3261683ffb44cedab1badb3096c7efb6064dbcc76e32817036ab8eb55c1502e7719721f9b9340dd2a0aea1df75df8bae055dce7aeceef78d77bc402de86caf582d7d198be3d8df2fcef8ccf7f0d2c0a8260ec4b0acc784e80c290661bb970ee5389780c4c69e2fce31aa7b8c03ec6773e30c071f24f91263c85b364140f28c7b97d72cc846666e47336bd9a013ce29ce772db3ab8b9c6c9cfb51e833ab40fbfa2209d2ef7e9230b4c4d5a8f98d4579ea622b55723ac29ed65bcec706f65e7db3961daad4ed63636a86db6007dc2c8ee356b7b5b5bc3bcdfd716fa53783e97c2682e10dd70c1a78bbc1c7f3ce41f1f28f9794907cd8d7e6c5df3f09ba008bd1c50e8cd274e497a9c87d5047ea0c3752fabab885d84eaec318f71877bc879dee4aefd3677bfa3bd1f1de73bf0c4c781c1fc4c75e316df22d0f95777cabd9e5294f321f7a1547d0c9beb89bf5dcdfaf7cfd4673ec3cff678b7bf6bbde5c7eeeaaf865bfc404be7e97f3d4ef99427d2c1bee665f7941fb13bfdbb83ed831f8405fd0c8fec2dffb409ff6acff
Segmentation fault (core dumped)

Is this normal, or how can I fix it ?

**Comment by kdping** [comment]
and my machine is 4 cores, 8G memory VPS

**Comment by aabc** [comment]
What architecture? Bus error is quite unusual.

**Comment by kdping** [comment]
ubuntu 16.04;
lscpu:

> Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             4
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 42
Model name:            Intel Xeon E312xx (Sandy Bridge)
Stepping:              1
CPU MHz:               2199.998
BogoMIPS:              4399.99
Virtualization:        VT-x
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl eagerfpu pni pclmulqdq vmx ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm vnmi ept fsgsbase smep erms xsaveopt

**Comment by aabc** [comment]
Show me your `input.bin` pls.

**Comment by kdping** [comment]
check https://github.com/kdping/blockheader-generator

**Comment by kdping** [comment]
Correct me if my input.bin is wrong, thx in advance.

**Comment by aabc** [comment]
Thanks, I will check it a bit later.

**Comment by aabc** [comment]
Fixed it. Big thanks for reporting!
